### ISSUE TITLE
Asset Pipeline

### ISSUE THREAD

**Issue by niallobrien** [clocklimited/BasicExpressSite#5]
Would you be open to moving the asset compilation over to Gulp?
If so, I could probably work on a PR for this. :)

**Comment by bengourley** [comment]
No thanks @niallobrien, this repo is purely here to support this article so it needs to remain the same:
http://www.clock.co.uk/blog/a-simple-website-in-nodejs-with-express-jade-and-stylus

Thanks for the suggestion though :smile:.

**Comment by niallobrien** [comment]
Ah, in that sense it makes perfect sense. Thanks.
